//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMarket.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentMarket.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        public static string DevMsg_Invalid {
            get {
                return ResourceManager.GetString("DevMsg_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm duyệt thành công.
        /// </summary>
        public static string UsrMsg_ApprovedSuccess {
            get {
                return ResourceManager.GetString("UsrMsg_ApprovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công.
        /// </summary>
        public static string UsrMsg_ChangePassSuccess {
            get {
                return ResourceManager.GetString("UsrMsg_ChangePassSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá thành công.
        /// </summary>
        public static string UsrMsg_DeleteSuccess {
            get {
                return ResourceManager.GetString("UsrMsg_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên với bộ phận chăm sóc khách hàng.
        /// </summary>
        public static string UsrMsg_Exception {
            get {
                return ResourceManager.GetString("UsrMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không chính xác.
        /// </summary>
        public static string UsrMsg_IncorrectPassword {
            get {
                return ResourceManager.GetString("UsrMsg_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công.
        /// </summary>
        public static string UsrMsg_InsertSuccess {
            get {
                return ResourceManager.GetString("UsrMsg_InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai thông tin đăng nhập.
        /// </summary>
        public static string UsrMsg_LoginFailed {
            get {
                return ResourceManager.GetString("UsrMsg_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập không được bỏ trống.
        /// </summary>
        public static string UsrMsg_LoginInfoEmpty {
            get {
                return ResourceManager.GetString("UsrMsg_LoginInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        public static string UsrMsg_LoginSuccess {
            get {
                return ResourceManager.GetString("UsrMsg_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bản ghi thoả mãn.
        /// </summary>
        public static string UsrMsg_NotFoundRecord {
            get {
                return ResourceManager.GetString("UsrMsg_NotFoundRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không tồn tại.
        /// </summary>
        public static string UsrMsg_NotFoundUserName {
            get {
                return ResourceManager.GetString("UsrMsg_NotFoundUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được bỏ trống.
        /// </summary>
        public static string UsrMsg_PasswordEmpty {
            get {
                return ResourceManager.GetString("UsrMsg_PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string UsrMsg_UpdateSuccess {
            get {
                return ResourceManager.GetString("UsrMsg_UpdateSuccess", resourceCulture);
            }
        }
    }
}
